# remote_theme: pmarsceill/just-the-docs
remote_theme: carlosperate/jekyll-theme-rtd

logo: "fig/mrs_logo.png"

title: "Multi-robot Systems Group UAV System"

url: "https://ctu-mrs.github.io"

aux_links:
  "MRS website":
    - "//mrs.felk.cvut.cz"
  "MRS Github":
    - "//github.com/ctu-mrs"
  "MRS UAV System":
    - "//github.com/ctu-mrs/mrs_uav_systtem"
